# Generated by Django 5.2.17 on 2026-09-29 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Customer Selling Price', max_digits=12)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Dealer Purchase Cost (Confidential)', max_digits=12)),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], db_index=True, default='Petrol', max_length=30)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Semi-Automatic', 'Semi-Automatic')], db_index=True, default='Automatic', max_length=30)),
                ('mileage', models.PositiveIntegerField(help_text='Odometer reading in kilometers')),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Truck', 'Truck'), ('Wagon', 'Wagon')], db_index=True, default='Sedan', max_length=30)),
                ('engine', models.CharField(blank=True, default='', max_length=100)),
                ('horsepower', models.PositiveIntegerField(default=0)),
                ('torque', models.PositiveIntegerField(default=0, help_text='Torque in Nm')),
                ('seats', models.PositiveIntegerField(default=5)),
                ('top_speed', models.PositiveIntegerField(default=0, help_text='Top speed in km/h')),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of vehicle feature strings')),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('UNAVAILABLE', 'Unavailable')], db_index=True, default='AVAILABLE', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'model'], name='vehicles_ve_brand_28f206_idx'), models.Index(fields=['status', 'price'], name='vehicles_ve_status_702b5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/gallery/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='vehicles.vehicle')),
            ],
        ),
    ]
