# Generated by Django 5.2.17 on 2026-09-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_color_alter_vehicle_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='External image URL or fallback', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Supercar', 'Supercar'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Truck', 'Truck'), ('Wagon', 'Wagon')], db_index=True, default='Sedan', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Plug-in Hybrid', 'Plug-in Hybrid'), ('Mild Hybrid', 'Mild Hybrid'), ('Pure Electric', 'Pure Electric')], db_index=True, default='Petrol', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Semi-Automatic', 'Semi-Automatic'), ('Dual-Clutch', 'Dual-Clutch'), ('Direct Drive', 'Direct Drive')], db_index=True, default='Automatic', max_length=30),
        ),
    ]
