# Generated by Django 5.2.17 on 2026-09-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_image_url_alter_vehicle_body_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Vehicle Identification Number / Chassis Number', max_length=50),
        ),
    ]
