# Generated by Django 5.2.17 on 2026-09-29 18:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_vehicle', models.CharField(blank=True, default='', help_text='Custom vehicle make/model if not from inventory', max_length=200)),
                ('service_type', models.CharField(choices=[('Oil & Filter Change', 'Oil & Filter Change'), ('Brake Service', 'Brake Service & Replacement'), ('Full Inspection', 'Comprehensive Vehicle Inspection'), ('Engine Diagnostics', 'Engine Diagnostics & Tuning'), ('Tire Service', 'Tire Rotation & Alignment'), ('Transmission Service', 'Transmission Fluid & Check'), ('Electrical', 'Battery & Electrical Diagnostics'), ('AC Service', 'Air Conditioning & Climate Control'), ('Custom Request', 'Custom Service / Repair')], default='Full Inspection', max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('dealer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_appointments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_appointments', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-preferred_date', '-preferred_time'],
            },
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('dealer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-preferred_date', '-preferred_time'],
            },
        ),
    ]
