# Generated by Django 5.2 on 2026-09-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('color', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
