# Generated by Django 5.2.17 on 2026-09-29 18:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Inventory Purchase / Stock In'), ('SALE', 'Customer Sale / Stock Out'), ('RETURN', 'Customer Return'), ('ADJUSTMENT', 'Inventory Adjustment'), ('DAMAGE', 'Damaged Stock Write-off')], db_index=True, default='PURCHASE', max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for addition, negative for deduction')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit purchase cost', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total value based on purchase cost', max_digits=12)),
                ('reference', models.CharField(blank=True, default='', help_text='Order / Invoice / Audit Reference', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='parts.part')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
