# Generated by Django 5.2.17 on 2026-09-29 18:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('VEHICLE', 'Vehicle Sale'), ('PART', 'Parts & Accessories Order'), ('SERVICE', 'Service Revenue')], db_index=True, default='VEHICLE', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Direct product cost', max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Direct labor / preparation / logistics', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net customer billing', max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, help_text='Gross profit = net_amount - direct costs', max_digits=12)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PAID', max_length=20)),
                ('sale_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.order')),
                ('service_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='services.serviceappointment')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
    ]
