# Generated by Django 5.2.17 on 2026-09-29 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RENT', 'Facility Rent & Lease'), ('SALARY', 'Payroll & Commissions'), ('UTILITIES', 'Electricity, Water & Internet'), ('MARKETING', 'Advertising & Marketing'), ('MAINTENANCE', 'Tools & Equipment Maintenance'), ('TRANSPORT', 'Vehicle Logistics & Shipping'), ('SUPPLIES', 'Office & Shop Supplies'), ('INSURANCE', 'Dealership & Liability Insurance'), ('TAX', 'Business Taxes & Municipal Fees'), ('OTHER', 'Miscellaneous Expenses')], db_index=True, default='OTHER', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Operating expense amount', max_digits=12)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(blank=True, default='Bank Transfer', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
