# Generated by Django 5.2.17 on 2026-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('Brakes', 'Brakes'), ('Suspension', 'Suspension'), ('Engine', 'Engine & Performance'), ('Exhaust', 'Exhaust System'), ('Wheels & Tires', 'Wheels & Tires'), ('Electrical', 'Electrical & Lighting'), ('Interior', 'Interior Accessories'), ('Exterior', 'Body & Exterior'), ('Service & Maintenance', 'Fluids & Filters'), ('Other', 'Other Accessories')], db_index=True, default='Other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Confidential supplier/purchase cost', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Customer retail price', max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=5, help_text='Threshold for low-stock warnings')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('compatibility', models.CharField(blank=True, default='', help_text='e.g. BMW M3/M4, Porsche 911, Universal', max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out of Stock'), ('DISCONTINUED', 'Discontinued')], db_index=True, default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'status'], name='parts_part_categor_62fc00_idx'), models.Index(fields=['brand', 'name'], name='parts_part_brand_8128e2_idx')],
            },
        ),
    ]
