# Generated by Django 5.2 on 2026-09-23 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('inquiry', 'Inquiry'), ('booking', 'Booking'), ('sold', 'Sold'), ('delivered', 'Delivered')], default='inquiry', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.vehicle')),
            ],
        ),
    ]
